--- #YAML:1.0
name:                DateTime-Format-Oracle
version:             0.05
abstract:            Parse and format Oracle dates and timestamps
license:             ~
author:              
    - Nathan Gray <kolibrie@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Convert::NLS_DATE_FORMAT:      0
    DateTime:                      0
    DateTime::Format::Builder:     0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
